image: golang:1.6

before_script:
  - "go get -u maunium.net/go/mauth"
  - "go get -u maunium.net/go/maulogger"
  - "go get -u github.com/go-sql-driver/mysql"
  - "go get -u github.com/ogier/pflag"
#  - "rm -f $GOPATH/src/maunium.net/go/mauimageserver"
#  - "ln -s $(pwd) $GOPATH/src/maunium.net/go/mauimageserver"

build:
  script:
    - "go build"
    - "mv mis2 mauimageserver"
  stage: build
  tags:
    - golang
  artifacts:
    paths:
    - mauimageserver
    - config.json
    - LICENSE
