variables:
  GOROOT: "/usr/local/go"
  GOPATH: "/home/gitlab-runner/go"

before_script:
  - "$GOROOT/bin/go get -u maunium.net/go/mauth"
  - "$GOROOT/bin/go get -u maunium.net/go/maulogger"
  - "$GOROOT/bin/go get -u github.com/go-sql-driver/mysql"
  - "$GOROOT/bin/go get -u github.com/ogier/pflag"
  - "rm -f $GOPATH/src/maunium.net/go/mauimageserver"
  - "ln -s $(pwd) $GOPATH/src/maunium.net/go/mauimageserver"
#  - "$GOROOT/bin/go get -u maunium.net/go/mauimageserver"

mainjob:
  script:
    - "$GOROOT/bin/go build"
    - "mv mis2 mauimageserver"
  stage: build
  tags:
    - golang

artifacts:
  paths:
  - mauimageserver
